apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-persistent-volume-claim
  namespace: media
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: media-persistent-volume

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-media-persistent-volume-claim
  namespace: media
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: data-media-persistent-volume
