apiVersion: apps/v1
kind: Deployment
metadata:
  name: homarr-deployment
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      apps: homarr
  template:
    metadata:
      name: homarr-pod
      labels:
        apps: homarr
    spec:
      containers:
        - name: homarr
          image: ghcr.io/ajnart/homarr:latest
          ports:
            - containerPort: 7575