apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      apps: webserver
  template:
    metadata:
      name: httpd-pod
      labels:
        apps: webserver
    spec:
      containers:
        - name: httpd
          image: httpd
          ports:
            - containerPort: 80