apiVersion: v1
kind: PersistentVolume
metadata:
  name: apps-persistent-volume
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/apps"
  claimRef:
    namespace: apps
    name: apps-persistent-volume-claim

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-apps-persistent-volume
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
  claimRef:
    namespace: apps
    name: data-apps-persistent-volume-claim
