apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apps-persistent-volume-claim
  namespace: apps
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: "apps-persistent-volume"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-apps-persistent-volume-claim
  namespace: apps
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: "data-apps-persistent-volume"
