apiVersion: v1
data:
  X-Different-Name: "true"
  X-Request-Start: t=${msec}
  X-Using-Nginx-Controller: "true"
  Cross-Origin-Embedder-Policy: "require-corp"
  Cross-Origin-Opener-Policy: "same-origin"
  Cross-Origin-Resource-Policy: "same-site"
kind: ConfigMap
metadata:
  name: custom-headers
  namespace: ingress-nginx
